name: Lint with Ruff (uv)

on:
  pull_request:
    branches:
      - main

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Testing steps
        run: echo "Hello world"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run Ruff for test.py
        run: uv run ruff check ./src/api/test.py

      - name: Run Ruff for league.py
        run: uv run ruff check ./src/api/league.py